onlyBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver

overrides:
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
