import {
  LogIn,
  Eye,
  EyeOff,
  Lock,
  User,
  Hotel,
  LayoutDashboard,
  DoorOpen,
  Calendar,
  CreditCard,
  Users,
  Settings,
  LogOut,
  Menu,
  X,
  Search,
  Filter,
  Plus,
  Edit,
  Trash2,
  Check,
  AlertCircle,
  Info,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  MoreVertical,
  Home,
  BedDouble,
  TrendingUp,
  DollarSign,
  UserCheck,
  Clock,
  Utensils,
  Receipt,
  FileText,
  BarChart3,
  ClipboardList,
  UserCog,
  CalendarDays,
  CalendarCheck,
  XCircle,
  Save,
  Download,
  PieChart,
  LineChart,
  BarChart2,
  Printer,
  CircleDollarSign,
  AlertTriangle,
  Wine,
  Shirt,
  Sparkles,
  Car,
  Package,
  CheckCircle,
  Pause,
  Mail,
  Phone,
  Shield,
  UserPlus,
  UserX,
  Loader2,
} from "lucide-react";

export const ICONS = {
  LOGIN: <LogIn />,
  EYE: <Eye />,
  EYE_OFF: <EyeOff />,
  LOCK: <Lock />,
  USER: <User />,
  HOTEL: <Hotel />,
  DASHBOARD: <LayoutDashboard />,
  DOOR_OPEN: <DoorOpen />,
  CALENDAR: <Calendar />,
  CREDIT_CARD: <CreditCard />,
  USERS: <Users />,
  SETTINGS: <Settings />,
  LOGOUT: <LogOut />,
  MENU: <Menu />,
  CLOSE: <X />,
  SEARCH: <Search />,
  FILTER: <Filter />,
  PLUS: <Plus />,
  EDIT: <Edit />,
  TRASH: <Trash2 />,
  CHECK: <Check />,
  ALERT: <AlertCircle />,
  INFO: <Info />,
  CHEVRON_DOWN: <ChevronDown />,
  CHEVRON_RIGHT: <ChevronRight />,
  CHEVRON_LEFT: <ChevronLeft />,
  MORE: <MoreVertical />,
  HOME: <Home />,
  BED_DOUBLE: <BedDouble />,
  TRENDING_UP: <TrendingUp />,
  DOLLAR_SIGN: <DollarSign />,
  USER_CHECK: <UserCheck />,
  CLOCK: <Clock />,
  UTENSILS: <Utensils />,
  RECEIPT: <Receipt />,
  FILE_TEXT: <FileText />,
  BAR_CHART: <BarChart3 />,
  CLIPBOARD_LIST: <ClipboardList />,
  USER_COG: <UserCog />,
  CALENDAR_DAYS: <CalendarDays />,
  CALENDAR_CHECK: <CalendarCheck />,
  X_CIRCLE: <XCircle />,
  SAVE: <Save />,
  DOWNLOAD: <Download />,
  PIE_CHART: <PieChart />,
  LINE_CHART: <LineChart />,
  BAR_CHART_2: <BarChart2 />,
  PRINTER: <Printer />,
  SURCHARGE: <CircleDollarSign />,
  PENALTY: <AlertTriangle />,
  WINE: <Wine />,
  SHIRT: <Shirt />,
  SPA: <Sparkles />,
  CAR: <Car />,
  PACKAGE: <Package />,
  CHECK_CIRCLE: <CheckCircle />,
  PAUSE: <Pause />,
  X: <X />,
  MAIL: <Mail />,
  PHONE: <Phone />,
  SHIELD: <Shield />,
  USER_PLUS: <UserPlus />,
  USER_X: <UserX />,
  MORE_VERTICAL: <MoreVertical />,
  ALERT_CIRCLE: <AlertCircle />,
  LOADER: <Loader2 />,
};
