import { PricingPolicy } from "@/lib/types/pricing";

// Mock Pricing Policies based on CHINHSACH_GIA database structure
export const mockPricingPolicies: PricingPolicy[] = [
  {
    MaChinhSach: "CS001",
    TenChinhSach: "Giá ngày thường - Standard",
    MaLoaiPhong: "STD",
    TenLoaiPhong: "Standard",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Ngày thường",
    HeSo: 1.0,
    MucUuTien: 1,
  },
  {
    MaChinhSach: "CS002",
    TenChinhSach: "Giá cuối tuần - Standard",
    MaLoaiPhong: "STD",
    TenLoaiPhong: "Standard",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Cuối tuần",
    HeSo: 1.4,
    MucUuTien: 2,
  },
  {
    MaChinhSach: "CS003",
    TenChinhSach: "Giá ngày lễ - Standard",
    MaLoaiPhong: "STD",
    TenLoaiPhong: "Standard",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Ngày lễ",
    HeSo: 1.8,
    MucUuTien: 3,
  },
  {
    MaChinhSach: "CS004",
    TenChinhSach: "Giá ngày thường - Deluxe",
    MaLoaiPhong: "DLX",
    TenLoaiPhong: "Deluxe",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Ngày thường",
    HeSo: 1.0,
    MucUuTien: 1,
  },
  {
    MaChinhSach: "CS005",
    TenChinhSach: "Giá cuối tuần - Deluxe",
    MaLoaiPhong: "DLX",
    TenLoaiPhong: "Deluxe",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Cuối tuần",
    HeSo: 1.25,
    MucUuTien: 2,
  },
  {
    MaChinhSach: "CS006",
    TenChinhSach: "Giá ngày lễ - Deluxe",
    MaLoaiPhong: "DLX",
    TenLoaiPhong: "Deluxe",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Ngày lễ",
    HeSo: 1.625,
    MucUuTien: 3,
  },
  {
    MaChinhSach: "CS007",
    TenChinhSach: "Mùa cao điểm Tết - Tất cả phòng",
    MaLoaiPhong: "ALL",
    TenLoaiPhong: "Tất cả loại phòng",
    TuNgay: "2025-01-28",
    DenNgay: "2025-02-04",
    KieuNgay: "Tất cả",
    HeSo: 2.0,
    MucUuTien: 5,
  },
  {
    MaChinhSach: "CS008",
    TenChinhSach: "Giá ngày thường - Suite",
    MaLoaiPhong: "SUT",
    TenLoaiPhong: "Suite",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Ngày thường",
    HeSo: 1.0,
    MucUuTien: 1,
  },
  {
    MaChinhSach: "CS009",
    TenChinhSach: "Giá cuối tuần - Suite",
    MaLoaiPhong: "SUT",
    TenLoaiPhong: "Suite",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Cuối tuần",
    HeSo: 1.25,
    MucUuTien: 2,
  },
  {
    MaChinhSach: "CS010",
    TenChinhSach: "Giá ngày lễ - Suite",
    MaLoaiPhong: "SUT",
    TenLoaiPhong: "Suite",
    TuNgay: "2025-01-01",
    DenNgay: "2025-12-31",
    KieuNgay: "Ngày lễ",
    HeSo: 1.5,
    MucUuTien: 3,
  },
  {
    MaChinhSach: "CS011",
    TenChinhSach: "Black Friday - Standard",
    MaLoaiPhong: "STD",
    TenLoaiPhong: "Standard",
    TuNgay: "2025-11-28",
    DenNgay: "2025-11-30",
    KieuNgay: "Tất cả",
    HeSo: 0.7,
    MucUuTien: 4,
  },
  {
    MaChinhSach: "CS012",
    TenChinhSach: "Khuyến mãi hè - Deluxe",
    MaLoaiPhong: "DLX",
    TenLoaiPhong: "Deluxe",
    TuNgay: "2025-06-01",
    DenNgay: "2025-08-31",
    KieuNgay: "Ngày thường",
    HeSo: 0.85,
    MucUuTien: 4,
  },
];
